# Generated by Django 2.1.1 on 2018-09-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AprioriResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Set_Of_Categories', models.CharField(default='None', max_length=500)),
                ('Support', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('Name_Of_Community', models.CharField(default='None', max_length=200)),
                ('FAMobility', models.IntegerField()),
                ('FASafety', models.IntegerField()),
                ('SAEconomic', models.IntegerField()),
                ('SARoadsTrans', models.IntegerField()),
                ('TArtificialIntelligence', models.IntegerField()),
                ('TAutonomousVehicles', models.IntegerField()),
                ('TGeospatial', models.IntegerField()),
                ('TIoT', models.IntegerField()),
                ('TSensors', models.IntegerField()),
                ('city_id', models.PositiveIntegerField(default=0, help_text='This is this is the city id which will be used in the campaign information page to retrieve data for each campaign', primary_key=True, serialize=False)),
            ],
        ),
    ]
