# Generated by Django 2.1.1 on 2018-09-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicpark', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='grger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Set_Of_Categories', models.CharField(default='None', max_length=500)),
                ('Support', models.FloatField()),
            ],
        ),
    ]
