# Generated by Django 2.1.2 on 2018-10-01 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civicpark', '0002_grger'),
    ]

    operations = [
        migrations.DeleteModel(
            name='grger',
        ),
    ]
